title: "MW122 - Topics in Econometrics and Data Science   "
description: "Prof. Dr. Jannis Kück<br>Alexandra Gibbon (M.Sc.)<br>Mara Mattes (M.Sc.)"
affiliation: "Düsseldorf Institute for Competition Economics (DICE), Heinrich Heine University Düsseldorf"

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

